### ISSUE TITLE
About the Feature File 'CLIP-ViT-B-16-views-st-samefilter.hdf5'

### ISSUE THREAD

**Issue by Feliciaxyao** [CrystalSixone/VLN-GOAT#1]
Use the feature file  'CLIP-ViT-B-16-views-st-samefilter.hdf5' during finetuning，get an error：
OSError: Unable to open file (file signature not found)
![VLN-GOAT](https://github.com/CrystalSixone/VLN-GOAT/assets/100859216/86d3b57c-41d9-48e8-8068-bd2f71d8e66a)

**Comment by CrystalSixone** [comment]
I am sorry that I uploaded a soft link file before, and it has been corrected now.

**Comment by Feliciaxyao** [comment]
The problem has been solved. Thanks for your perfect work！

**Comment by CelestinoMelodyLumiere** [comment]
> The problem has been solved. Thanks for your perfect work！

Excuse me, sir/madam. I'm encountering the same issue with the HDF5 file not being found. If you have time, could you please help me solve it as well? Here are some additional details about my setup and the error I'm facing:

Error Message: FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../datasets/EnvEdit/hamt_features/CLIP-ViT-B-16-views-st-samefilter.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by jj023721** [comment]
你好，这里是ylJiang，你的邮件已收到！

**Comment by Feliciaxyao** [comment]
> > The problem has been solved. Thanks for your perfect work！
> 
> Excuse me, sir/madam. I'm encountering the same issue with the HDF5 file not being found. If you have time, could you please help me solve it as well? Here are some additional details about my setup and the error I'm facing:
> 
> Error Message: FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../datasets/EnvEdit/hamt_features/CLIP-ViT-B-16-views-st-samefilter.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

![image](https://github.com/user-attachments/assets/35029f88-20de-4aef-91a6-ed4eb7af6d12)
Hello, CelestinoMelodyLumiere! The file is available [here](https://huggingface.co/crystal61/VLN-GOAT), in the link for Datasets, Features and Trained-weights.

**Comment by CelestinoMelodyLumiere** [comment]
> e problem has been solved. Thanks for your perfect work！
Thank you very much for your prompt and detailed response. If I encounter any more issues or need further assistance, I will certainly reach out. Your help is greatly appreciated. Wishing you a pleasant and productive day!
