### ISSUE TITLE
R2R evaluation results

### ISSUE THREAD

**Issue by leyuan-sun** [CrystalSixone/VLN-GOAT#11]
After command bash scripts/run_r2r_valid.sh, in valid.txt, I obtained numbers "Env name: val_train_seen, Env name: val_seen, and Env name: val_unseen", but I got 4 trajectory json file including submit_text.json, why? 
Which ones represent the _validation seen, validation unseen and test unseen_ you provided in the Table.1 of the paper?

**Comment by CrystalSixone** [comment]
When you run run_r2r_valid.sh, you can obtain four submit_text.json files, which are used to be uploaded on the [online leaderboard](https://eval.ai/web/challenges/challenge-page/97/overview) to get the metrics. This is useful to get the test_unseen result. The other val_seen and val_unseen results can be directly obtained from valid.txt.

**Comment by leyuan-sun** [comment]
Thanks, which means all the test_unseen results muse be evaluated by online leaderboard?

**Comment by CrystalSixone** [comment]
Yes. This is for a fair comparison.
