### ISSUE TITLE
simulator problem

### ISSUE THREAD

**Issue by zhouak47** [CrystalSixone/VLN-GOAT#2]
Thanks for your great job.when installing MatterPort3D Simulator i wonder whether to use  dockor to install matterport3D. Do you use docker to install MatterPort3D Simulator? Please tell me .thanks.

**Comment by CrystalSixone** [comment]
I didn't use docker to install the MP3D simulator since I found it could also face the version problem. I recommend compiling and installing it directly.

**Comment by zhouak47** [comment]
Thanks a lot for your reply
