### ISSUE TITLE
GFLOPs calculation

### ISSUE THREAD

**Issue by eazook10003** [CrystalSixone/VLN-GOAT#5]
I want to say that your work is amazing and has been incredibly helpful! I’m trying to calculate GFLOPs for HAMT(VLN) but it seems to be not straight forward where it consists with multiple transformers(Should I sum the GFLOPs for each transformer to get the total GFLOPs?). It would be helpful if you could provide the details about FLOPs calculation.

**Comment by CrystalSixone** [comment]
Hi! First of all, thank you very much for acknowledging our work.

I have updated the code for computing model efficiency, including the number of parameters and GFLOPs. You can calculate these metrics using the following command:
```
cd map_nav_src
bash scripts/model_efficiency_count.sh
```
Please note that we computed only a single step for each forward pass. I hope this helps you in computing GFLOPs for other similar methods.

**Comment by eazook10003** [comment]
Thank you so much!
