### ISSUE TITLE
How can I download the EnvEdit dataset?

### ISSUE THREAD

**Issue by yds3** [CrystalSixone/VLN-GOAT#7]
Hello, dear author. May I ask how to download the EnvEdit dataset? Should I fill out a Matterport application form and send it to jialuli@cs.unc.edu via email?

**Comment by CrystalSixone** [comment]
You can download the extracted features from the EnvEdit repository: https://github.com/jialuli-luka/EnvEdit. If you only need to reprocess the raw images, please contact Jialu for approval. Otherwise, you can use the provided extracted features directly without requesting the raw images.
